# Generated by Django 3.0.6 on 2020-06-17 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_delete_venue'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='property',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='property.Property'),
        ),
    ]
