# Generated by Django 3.0.6 on 2020-06-17 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_delete_venue'),
        ('contact', '0005_auto_20200617_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='property',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='property.Property'),
        ),
    ]
