# Generated by Django 3.0.6 on 2020-06-17 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20200617_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='property_id',
        ),
    ]
