# Generated by Django 3.0.6 on 2020-06-19 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_remove_inquiry_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='contact_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='property_details',
            field=models.CharField(default=15, max_length=200),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='property_id',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='user_id',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
