# Generated by Django 3.0.6 on 2020-06-19 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_auto_20200619_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='contact_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 19, 11, 59, 14, 493648)),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='property_details',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='property_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='user_id',
            field=models.IntegerField(blank=True),
        ),
    ]
