# Generated by Django 3.0.6 on 2020-06-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_auto_20200619_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='contact_date',
            new_name='inquiry_date',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='property_details',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='property_id',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='user_id',
        ),
    ]
