# Generated by Django 3.0.6 on 2020-06-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_auto_20200619_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='property_detail',
            field=models.CharField(default='some', max_length=250),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='property_id',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='user_id',
            field=models.IntegerField(blank=True, default=15),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry_name',
            field=models.CharField(max_length=200),
        ),
    ]
