# Generated by Django 3.0.6 on 2020-06-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0014_auto_20200622_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='property_detail',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='property_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='user_id',
            field=models.IntegerField(blank=True),
        ),
    ]
