# Generated by Django 3.0.6 on 2020-06-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0015_auto_20200622_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='property_image',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
