# Generated by Django 3.0.6 on 2020-06-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realtor_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('realtor_description', models.TextField()),
                ('realtor_image', models.ImageField(upload_to='media/%Y/%m/%d')),
                ('mobile', models.IntegerField()),
                ('hire_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.CharField(choices=[('0', 'Active'), ('1', 'Inactive')], max_length=2)),
                ('is_deleted', models.CharField(choices=[('0', 'Active'), ('1', 'Inactive')], max_length=2)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=100)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
