# Generated by Django 3.0.6 on 2020-06-10 07:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtors',
            name='realtor_description',
            field=tinymce.models.HTMLField(),
        ),
    ]
