# Generated by Django 3.0.6 on 2020-06-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_auto_20200610_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtors',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='realtors',
            name='mobile',
            field=models.TextField(),
        ),
    ]
