# Generated by Django 3.0.6 on 2020-06-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0004_auto_20200610_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtors',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
