# Generated by Django 3.0.6 on 2020-06-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0005_auto_20200610_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtors',
            name='realtor_image',
        ),
    ]
