# Generated by Django 3.0.6 on 2020-06-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0006_remove_realtors_realtor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtors',
            name='realtor_image',
            field=models.ImageField(default='some image', upload_to='media/%Y/%m/%d'),
        ),
    ]
