# Generated by Django 3.0.6 on 2020-06-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0007_realtors_realtor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtors',
            name='realtor_image',
            field=models.ImageField(upload_to='media/%Y/%m/%d'),
        ),
    ]
