# Generated by Django 3.0.6 on 2020-06-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0010_remove_realtors_hire_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtors',
            name='is_deleted',
        ),
    ]
