# Generated by Django 3.0.6 on 2020-06-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0011_remove_realtors_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtors',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
