# Generated by Django 3.0.6 on 2020-06-17 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0012_realtors_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtors',
            name='is_published',
        ),
    ]
