# Generated by Django 3.0.6 on 2020-06-23 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0015_auto_20200622_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtors',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
