# Generated by Django 3.0.6 on 2020-06-30 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0018_auto_20200630_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtors',
            old_name='username',
            new_name='realtor_username',
        ),
    ]
