# Generated by Django 3.0.6 on 2020-06-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0019_auto_20200630_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtors',
            name='is_active',
        ),
    ]
