# Generated by Django 3.0.6 on 2020-06-10 07:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20200610_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
