# Generated by Django 3.0.6 on 2020-06-11 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20200610_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='property',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='property',
            name='updated_date',
        ),
    ]
