# Generated by Django 3.0.6 on 2020-06-11 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20200611_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='created_by',
        ),
    ]
