# Generated by Django 3.0.6 on 2020-06-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_remove_property_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_slug',
            field=models.SlugField(default='Slug', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_image1',
            field=models.FileField(upload_to='media/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_image_main',
            field=models.FileField(upload_to='media/%Y/%m/%d'),
        ),
    ]
