# Generated by Django 3.0.6 on 2020-06-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20200612_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_image2',
            field=models.FileField(default='some', upload_to='media/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_image3',
            field=models.FileField(default='some', upload_to='media/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_image4',
            field=models.FileField(default='some', upload_to='media/%Y/%m/%d'),
        ),
    ]
