# Generated by Django 3.0.6 on 2020-06-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20200612_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_image2',
            field=models.FileField(upload_to='media/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_image3',
            field=models.FileField(upload_to='media/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_image4',
            field=models.FileField(upload_to='media/%Y/%m/%d'),
        ),
    ]
