# Generated by Django 3.0.6 on 2020-06-12 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20200612_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_slug',
        ),
    ]
