# Generated by Django 3.0.6 on 2020-06-17 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_venue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
