# Generated by Django 3.0.6 on 2020-06-19 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20200617_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
