# Generated by Django 3.0.6 on 2020-06-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20200619_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='plot_size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='sqft',
            field=models.IntegerField(),
        ),
    ]
