# Generated by Django 3.0.6 on 2020-06-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20200619_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(),
        ),
    ]
