# Generated by Django 3.0.6 on 2020-06-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20200619_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_slug',
            field=models.SlugField(editable=False, max_length=1000),
        ),
    ]
