# Generated by Django 3.0.6 on 2020-06-23 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0015_auto_20200622_1121'),
        ('property', '0020_auto_20200622_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='inquiry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contact.Inquiry'),
        ),
    ]
