# Generated by Django 3.0.6 on 2020-06-25 05:56

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_remove_property_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('zipcode', models.IntegerField()),
                ('description', tinymce.models.HTMLField()),
                ('price', models.CharField(max_length=150)),
                ('rooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('sqft', models.IntegerField()),
                ('plot_size', models.IntegerField()),
                ('property_image_main', models.FileField(upload_to='media/%Y/%m/%d')),
                ('property_image1', models.FileField(blank=True, upload_to='media/%Y/%m/%d')),
                ('property_image2', models.FileField(blank=True, upload_to='media/%Y/%m/%d')),
                ('property_image3', models.FileField(blank=True, upload_to='media/%Y/%m/%d')),
                ('property_image4', models.FileField(blank=True, upload_to='media/%Y/%m/%d')),
                ('is_active', models.CharField(choices=[('0', 'Active'), ('1', 'Inactive')], max_length=2)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_property_slug', models.SlugField(editable=False, max_length=1000)),
            ],
        ),
    ]
