# Generated by Django 3.0.6 on 2020-06-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0028_auto_20200625_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_property',
            name='description',
            field=models.TextField(),
        ),
    ]
